language: ruby
cache: bundler
sudo: false

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system
  - gem uninstall bundler -a -x
  - gem install bundler --pre
  - rm -f .bundle/config

rvm:
  - 2.2.5
  - 2.3.1
script: bundle exec rake spec
