sudo: false
language: ruby
cache: bundler

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system
  - gem uninstall bundler -a -x
  - gem install bundler
  - rm -f .bundle/config

matrix:
  include:
    - rvm: 2.2.10
    - rvm: 2.3.7
    - rvm: 2.4.4
    - rvm: 2.5.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

script: bundle exec rake spec

branches:
  only:
  - master
