language: ruby
cache: bundler
dist: xenial

matrix:
  include:
    - rvm: 2.5.5
    - rvm: 2.6.3
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
    - 0-stable

bundler_args: --jobs 7 --without docs debug

script: bundle exec rake
