sudo: false
language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.3.7
    - rvm: 2.4.4
    - rvm: 2.5.1
    - rvm: ruby-head
  allow_failures:
    - rvm: ruby-head

branches:
  only:
  - master

bundler_args: --without docs development

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system
  - gem --version
  - rvm @global do gem uninstall bundler -a -x || true
  - gem install bundler
  - bundle --version
  - rm -f .bundle/config

script: bundle exec rake
